// Copyright 2025, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  Adreno/TBDR-native Gaussian-splat renderer — implementation.
 *
 * Per-eye pipeline (one command buffer, no GPU→CPU readback):
 *   updateUniforms → preprocess(N) → keygen(N) → radix sort(N) →
 *   instanced alpha-blended quad draw → blit (linear upscale) to swapchain.
 * See gs_adreno_renderer.h for the design rationale.
 */

#include "gs_adreno_renderer.h"
#include "gs_scene_loader.h"
#include "gs_spz_loader.h"

#include <cstdio>
#include <cstring>
#include <cmath>
#include <cfloat>
#include <algorithm>
#include <vector>

#if defined(__ANDROID__)
#  include <android/log.h>
#  include <sys/system_properties.h>
#  define GS_LOGI(...) __android_log_print(ANDROID_LOG_INFO, "gausssplat_vk_android", __VA_ARGS__)
#  define GS_LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "gausssplat_vk_android", __VA_ARGS__)
#else
#  define GS_LOGI(...) do { printf(__VA_ARGS__); printf("\n"); } while (0)
#  define GS_LOGE(...) do { fprintf(stderr, __VA_ARGS__); fprintf(stderr, "\n"); } while (0)
#endif

// ── SPIR-V shader includes (generated by CMake; var = <name>_data) ──
#include "precomp_cov3d.comp.h"
#include "adreno_preprocess.comp.h"
#include "hist.comp.h"
#include "sort.comp.h"
#include "splat_keys.comp.h"
#include "splat.vert.h"
#include "splat.frag.h"

// ── Uniform layout (std140, matches adreno_preprocess.comp Params) ──
struct alignas(16) GsUniformBuffer {
    float camera_position[4];
    float proj_mat[16];
    float view_mat[16];
    uint32_t width;
    uint32_t height;
    float tan_fovx;
    float tan_fovy;
    float clip_far;
    float clip_fade_frac;
    float clip_near;
};
static_assert(sizeof(GsUniformBuffer) == 176, "GsUniformBuffer must be 176 bytes");

// ═══════════════════════════ small Vulkan helpers ═══════════════════════════

static VkShaderModule makeModule(VkDevice d, const uint32_t* code, size_t bytes) {
    VkShaderModuleCreateInfo ci = {VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    ci.codeSize = bytes; ci.pCode = code;
    VkShaderModule m = VK_NULL_HANDLE;
    vkCreateShaderModule(d, &ci, nullptr, &m);
    return m;
}

static VkPipeline makeCompute(VkDevice d, VkPipelineLayout layout, VkShaderModule sh,
                              const VkSpecializationInfo* spec = nullptr) {
    VkComputePipelineCreateInfo ci = {VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
    ci.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    ci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    ci.stage.module = sh; ci.stage.pName = "main";
    ci.stage.pSpecializationInfo = spec;
    ci.layout = layout;
    VkPipeline p = VK_NULL_HANDLE;
    vkCreateComputePipelines(d, VK_NULL_HANDLE, 1, &ci, nullptr, &p);
    return p;
}

static VkDescriptorSetLayout makeDSL(VkDevice d, const std::vector<VkDescriptorType>& types,
                                     VkShaderStageFlags stage = VK_SHADER_STAGE_COMPUTE_BIT) {
    std::vector<VkDescriptorSetLayoutBinding> b(types.size());
    for (size_t i = 0; i < types.size(); i++) {
        b[i] = {};
        b[i].binding = (uint32_t)i;
        b[i].descriptorType = types[i];
        b[i].descriptorCount = 1;
        b[i].stageFlags = stage;
    }
    VkDescriptorSetLayoutCreateInfo ci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    ci.bindingCount = (uint32_t)b.size(); ci.pBindings = b.data();
    VkDescriptorSetLayout l = VK_NULL_HANDLE;
    vkCreateDescriptorSetLayout(d, &ci, nullptr, &l);
    return l;
}

static VkPipelineLayout makePipeLayout(VkDevice d,
                                       const std::vector<VkDescriptorSetLayout>& dsls,
                                       uint32_t pushSize,
                                       VkShaderStageFlags pushStage = VK_SHADER_STAGE_COMPUTE_BIT) {
    VkPushConstantRange pcr = {pushStage, 0, pushSize};
    VkPipelineLayoutCreateInfo ci = {VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    ci.setLayoutCount = (uint32_t)dsls.size(); ci.pSetLayouts = dsls.data();
    if (pushSize > 0) { ci.pushConstantRangeCount = 1; ci.pPushConstantRanges = &pcr; }
    VkPipelineLayout l = VK_NULL_HANDLE;
    vkCreatePipelineLayout(d, &ci, nullptr, &l);
    return l;
}

static VkDescriptorSet allocDS(VkDevice d, VkDescriptorPool pool, VkDescriptorSetLayout dsl) {
    VkDescriptorSetAllocateInfo ai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    ai.descriptorPool = pool; ai.descriptorSetCount = 1; ai.pSetLayouts = &dsl;
    VkDescriptorSet ds = VK_NULL_HANDLE;
    vkAllocateDescriptorSets(d, &ai, &ds);
    return ds;
}

static void writeDS(VkDevice d, VkDescriptorSet ds, uint32_t binding,
                    VkDescriptorType type, VkBuffer buf, VkDeviceSize range) {
    VkDescriptorBufferInfo bi = {buf, 0, range};
    VkWriteDescriptorSet w = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    w.dstSet = ds; w.dstBinding = binding; w.descriptorCount = 1;
    w.descriptorType = type; w.pBufferInfo = &bi;
    vkUpdateDescriptorSets(d, 1, &w, 0, nullptr);
}

// ═══════════════════════════════ init ═══════════════════════════════════════

bool GsAdrenoRenderer::init(VkInstance instance, VkPhysicalDevice physicalDevice,
                            VkDevice device, VkQueue queue, uint32_t queueFamilyIndex,
                            uint32_t renderWidth, uint32_t renderHeight) {
    instance_ = instance; physDevice_ = physicalDevice; device_ = device;
    queue_ = queue; queueFamily_ = queueFamilyIndex;
    width_ = renderWidth; height_ = renderHeight;

    // Subgroup size + timestamp support.
    VkPhysicalDeviceSubgroupProperties sg = {VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES};
    VkPhysicalDeviceProperties2 p2 = {VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2};
    p2.pNext = &sg;
    vkGetPhysicalDeviceProperties2(physDevice_, &p2);
    subgroupSize_ = sg.subgroupSize ? sg.subgroupSize : 32;
    timestampPeriod_ = p2.properties.limits.timestampPeriod;
    {
        uint32_t n = 0;
        vkGetPhysicalDeviceQueueFamilyProperties(physDevice_, &n, nullptr);
        std::vector<VkQueueFamilyProperties> qf(n);
        vkGetPhysicalDeviceQueueFamilyProperties(physDevice_, &n, qf.data());
        if (queueFamilyIndex < n) tsValidBits_ = qf[queueFamilyIndex].timestampValidBits;
    }

    // Render-scale: the whole pipeline runs at scale×eye dims then upscales the
    // blit. Per-fragment overdraw dominates, so this is a near-linear fps lever.
    renderScale_ = 1.0f;
    keepFrac_ = 1.0f;
#if defined(__ANDROID__)
    // Max-quality default: native resolution + all gaussians. On the NP02J this is
    // ~22 fps (vs ~48 at 0.45/0.25) — the team chose image quality over framerate
    // for the demo. debug.dxr.gs.scale / .keep still override live for perf sweeps.
    renderScale_ = 1.0f;
    keepFrac_ = 1.0f;
    {
        char v[PROP_VALUE_MAX] = {0};
        if (__system_property_get("debug.dxr.gs.scale", v) > 0) {
            float s = (float)atof(v);
            if (s > 0.05f) renderScale_ = s;
        }
        v[0] = 0;
        if (__system_property_get("debug.dxr.gs.keep", v) > 0) {
            float k = (float)atof(v);
            if (k > 0.01f && k <= 1.0f) keepFrac_ = k;
        }
    }
#endif
    if (renderScale_ < 0.2f) renderScale_ = 0.2f;
    if (renderScale_ > 1.0f) renderScale_ = 1.0f;

    VkCommandPoolCreateInfo pci = {VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
    pci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    pci.queueFamilyIndex = queueFamilyIndex;
    if (vkCreateCommandPool(device_, &pci, nullptr, &cmdPool_) != VK_SUCCESS) {
        GS_LOGE("GsAdreno: command pool create failed");
        return false;
    }

    // Frame-pipelining ring: kFrameRing command buffers + fences (start
    // signaled so the first kFrameRing submits don't wait on stale fences).
    {
        VkCommandBufferAllocateInfo cba = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        cba.commandPool = cmdPool_; cba.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        cba.commandBufferCount = kFrameRing;
        if (vkAllocateCommandBuffers(device_, &cba, ringCmd_) != VK_SUCCESS) {
            GS_LOGE("GsAdreno: ring cmd-buffer alloc failed"); return false;
        }
        VkFenceCreateInfo fci = {VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
        fci.flags = VK_FENCE_CREATE_SIGNALED_BIT;
        for (uint32_t i = 0; i < kFrameRing; i++)
            vkCreateFence(device_, &fci, nullptr, &ringFence_[i]);
        ringReady_ = true;
    }

    if (timestampPeriod_ > 0.0f && tsValidBits_ > 0) {
        VkQueryPoolCreateInfo q = {VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO};
        q.queryType = VK_QUERY_TYPE_TIMESTAMP; q.queryCount = kNumTimestamps;
        for (uint32_t i = 0; i < kFrameRing; i++) {
            if (vkCreateQueryPool(device_, &q, nullptr, &tsPool_[i]) != VK_SUCCESS) {
                for (uint32_t j = 0; j < kFrameRing; j++) {
                    if (tsPool_[j]) { vkDestroyQueryPool(device_, tsPool_[j], nullptr); tsPool_[j] = VK_NULL_HANDLE; }
                }
                timestampPeriod_ = 0.0f; break;
            }
        }
    } else {
        timestampPeriod_ = 0.0f;
    }

    initialized_ = true;
    GS_LOGI("GsAdreno: initialized (%ux%u eye, renderScale=%.2f, subgroup=%u, "
            "ts_period=%.2fns valid_bits=%u)",
            width_, height_, renderScale_, subgroupSize_, timestampPeriod_, tsValidBits_);
    return true;
}

// ═══════════════════════════════ loadScene ══════════════════════════════════

bool GsAdrenoRenderer::loadScene(const char* scenePath) {
    if (!initialized_) { GS_LOGE("GsAdreno: not initialized"); return false; }
    cleanupScene();

    std::vector<GsVertex> verts;
    std::string path(scenePath);
    std::string ext = path.substr(path.find_last_of('.'));
    std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
    bool ok = (ext == ".spz") ? ParseSpzFile(path, verts) : ParsePlyFile(path, verts);
    if (!ok || verts.empty()) { GS_LOGE("GsAdreno: parse failed: %s", scenePath); return false; }

    // Load-time decimation: keep ~keepFrac_ of the gaussians, hash-selected for
    // a spatially-uniform thinning independent of file order. Every stage
    // (preprocess, keygen, radix sort, instanced draw) scales with the count,
    // so this is a near-linear cut to per-eye GPU time. Soft overlapping splats
    // hide the thinning well on dense scenes like butterfly.
    if (keepFrac_ < 0.999f && verts.size() >= 1024) {
        const size_t total = verts.size();
        const uint32_t thresh = (uint32_t)(keepFrac_ * 65536.0f);
        size_t kept = 0;
        for (size_t i = 0; i < total; i++) {
            uint32_t h = ((uint32_t)i * 2654435761u) >> 16;  // Knuth multiplicative hash
            if ((h & 0xFFFFu) >= thresh) continue;
            verts[kept++] = verts[i];
        }
        if (kept >= 1024) {
            verts.resize(kept);
            GS_LOGI("GsAdreno: decimation keep=%.2f -> %zu/%zu gaussians",
                    (double)keepFrac_, kept, total);
        }
    }

    numGaussians_ = (uint32_t)verts.size();
    loadedScenePath_ = path;

    // CPU centers for auto-framing + the per-eye depth-quant range.
    posX_.resize(numGaussians_); posY_.resize(numGaussians_); posZ_.resize(numGaussians_);
    for (uint32_t i = 0; i < numGaussians_; i++) {
        posX_[i] = verts[i].position[0];
        posY_[i] = verts[i].position[1];
        posZ_[i] = verts[i].position[2];
    }
    // Outlier-trimmed [p2,p98] bbox (drives the sort depth quantization range).
    {
        std::vector<float> c(numGaussians_);
        const float* src[3] = {posX_.data(), posY_.data(), posZ_.data()};
        for (int a = 0; a < 3; a++) {
            std::copy(src[a], src[a] + numGaussians_, c.begin());
            size_t lo = (size_t)(0.02f * (float)(numGaussians_ ? numGaussians_ - 1 : 0));
            size_t hi = (size_t)(0.98f * (float)(numGaussians_ ? numGaussians_ - 1 : 0));
            if (hi <= lo) hi = lo + 1;
            if (hi >= numGaussians_) hi = numGaussians_ ? numGaussians_ - 1 : 0;
            std::nth_element(c.begin(), c.begin() + lo, c.end());
            float mn = c[lo];
            std::nth_element(c.begin() + lo + 1, c.begin() + hi, c.end());
            float mx = c[hi];
            sceneBBoxMin_[a] = mn; sceneBBoxMax_[a] = mx;
        }
        sceneBBoxValid_ = (numGaussians_ >= 16);
    }

    // Upload vertices.
    const VkBufferUsageFlags ssbo =
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    const VkMemoryPropertyFlags devLocal = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
    vertexBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)numGaussians_ * sizeof(GsVertex), ssbo, devLocal);
    if (!gsUploadBuffer(device_, physDevice_, queue_, cmdPool_, vertexBuffer_,
                        verts.data(), (VkDeviceSize)numGaussians_ * sizeof(GsVertex))) {
        GS_LOGE("GsAdreno: vertex upload failed");
        return false;
    }

    if (!createSceneResources()) { GS_LOGE("GsAdreno: createSceneResources failed"); return false; }
    dispatchCov3d();

    sceneLoaded_ = true;
    GS_LOGI("GsAdreno: scene loaded (%u gaussians, sort wg=%u)", numGaussians_, numSortWorkgroups_);
    return true;
}

// ═══════════════════════ createSceneResources ═══════════════════════════════

bool GsAdrenoRenderer::createSceneResources() {
    const uint32_t N = numGaussians_;
    const VkBufferUsageFlags ssbo =
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    const VkMemoryPropertyFlags devLocal = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
    const VkMemoryPropertyFlags hostVis =
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;

    // ── Buffers ──
    cov3dBuffer_   = gsCreateBuffer(device_, physDevice_, (VkDeviceSize)N * 24, ssbo, devLocal);
    attrBuffer_    = gsCreateBuffer(device_, physDevice_, (VkDeviceSize)N * 64, ssbo, devLocal);
    keysEvenBuffer_= gsCreateBuffer(device_, physDevice_, (VkDeviceSize)N * 4, ssbo, devLocal);
    keysOddBuffer_ = gsCreateBuffer(device_, physDevice_, (VkDeviceSize)N * 4, ssbo, devLocal);
    valsEvenBuffer_= gsCreateBuffer(device_, physDevice_, (VkDeviceSize)N * 4, ssbo, devLocal);
    valsOddBuffer_ = gsCreateBuffer(device_, physDevice_, (VkDeviceSize)N * 4, ssbo, devLocal);
    for (uint32_t s = 0; s < kFrameRing; s++)
        uniformBuffer_[s] = gsCreateBuffer(device_, physDevice_, sizeof(GsUniformBuffer),
                                           VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT, hostVis);

    // Radix sort workgroup sizing — parallelism, NOT just coverage. With a
    // fixed 256 blocks/workgroup the whole sort collapses onto 1 workgroup at
    // mobile N (44k → ceil(44k/65536)=1 WG = ~256 threads = a sliver of the
    // Adreno), which is why the sort dominated at ~10 ms for trivial work.
    // Instead pick blocks/WG so we dispatch ~kTargetSortWG workgroups to
    // saturate the GPU. (The desktop path got ~22 WG only incidentally, via its
    // N×8 fragment over-allocation.) Same sort, just spread across the cores.
    constexpr uint32_t kTargetSortWG = 64;
    numRadixBlocksPerWG_ = (N + 256u * kTargetSortWG - 1u) / (256u * kTargetSortWG);
    if (numRadixBlocksPerWG_ < 1u) numRadixBlocksPerWG_ = 1u;
    numSortWorkgroups_ = (N + numRadixBlocksPerWG_ * 256u - 1u) / (numRadixBlocksPerWG_ * 256u);
    if (numSortWorkgroups_ == 0) numSortWorkgroups_ = 1;
    histBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)numSortWorkgroups_ * 256 * 4, ssbo, devLocal);

    // Internal scaled render target (full size; only the scaled sub-rect used).
    renderImage_ = gsCreateImage2D(device_, physDevice_, width_, height_,
        VK_FORMAT_R8G8B8A8_UNORM,
        VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT);

    // ── Descriptor pool ──
    {
        VkDescriptorPoolSize sizes[2] = {
            {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 40},
            {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 4}};
        VkDescriptorPoolCreateInfo ci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
        ci.maxSets = 12; ci.poolSizeCount = 2; ci.pPoolSizes = sizes;
        if (vkCreateDescriptorPool(device_, &ci, nullptr, &descriptorPool_) != VK_SUCCESS)
            return false;
    }

    // ── precomp_cov3d (Vertices, Cov3Ds) + push scale_factor ──
    dslCov3d_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                  VK_DESCRIPTOR_TYPE_STORAGE_BUFFER});
    layoutCov3d_ = makePipeLayout(device_, {dslCov3d_}, sizeof(float));
    { VkShaderModule m = makeModule(device_, precomp_cov3d_comp_data, sizeof(precomp_cov3d_comp_data));
      pipeCov3d_ = makeCompute(device_, layoutCov3d_, m); vkDestroyShaderModule(device_, m, nullptr); }

    // ── preprocess: set0{Vertices,Cov3Ds} set1{Params(ubo),VertexAttributes} ──
    dslPreprocessSet0_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                           VK_DESCRIPTOR_TYPE_STORAGE_BUFFER});
    dslPreprocessSet1_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
                                           VK_DESCRIPTOR_TYPE_STORAGE_BUFFER});
    layoutPreprocess_ = makePipeLayout(device_, {dslPreprocessSet0_, dslPreprocessSet1_}, 0);
    { VkShaderModule m = makeModule(device_, adreno_preprocess_comp_data, sizeof(adreno_preprocess_comp_data));
      pipePreprocess_ = makeCompute(device_, layoutPreprocess_, m); vkDestroyShaderModule(device_, m, nullptr); }

    // ── keygen: attr → {keys, payloads} + push {count, depthMin, invRange} ──
    dslKeys_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                 VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                 VK_DESCRIPTOR_TYPE_STORAGE_BUFFER});
    layoutKeys_ = makePipeLayout(device_, {dslKeys_}, sizeof(uint32_t) + 2 * sizeof(float));
    { VkShaderModule m = makeModule(device_, splat_keys_comp_data, sizeof(splat_keys_comp_data));
      pipeKeys_ = makeCompute(device_, layoutKeys_, m); vkDestroyShaderModule(device_, m, nullptr); }

    // ── radix hist (keys, histograms) + sort (keys io, vals io, histograms) ──
    const uint32_t radixPush = 4 * sizeof(uint32_t);
    dslHist_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                 VK_DESCRIPTOR_TYPE_STORAGE_BUFFER});
    layoutHist_ = makePipeLayout(device_, {dslHist_}, radixPush);
    { VkShaderModule m = makeModule(device_, hist_comp_data, sizeof(hist_comp_data));
      pipeHist_ = makeCompute(device_, layoutHist_, m); vkDestroyShaderModule(device_, m, nullptr); }

    dslSort_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                 VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                 VK_DESCRIPTOR_TYPE_STORAGE_BUFFER});
    layoutSort_ = makePipeLayout(device_, {dslSort_}, radixPush);
    { VkShaderModule m = makeModule(device_, sort_comp_data, sizeof(sort_comp_data));
      VkSpecializationMapEntry e = {0, 0, sizeof(uint32_t)};
      VkSpecializationInfo si = {1, &e, sizeof(uint32_t), &subgroupSize_};
      pipeSort_ = makeCompute(device_, layoutSort_, m, &si); vkDestroyShaderModule(device_, m, nullptr); }

    // ── Render pass: single colour attachment = renderImage_ ──
    {
        VkAttachmentDescription color = {};
        color.format = VK_FORMAT_R8G8B8A8_UNORM;
        color.samples = VK_SAMPLE_COUNT_1_BIT;
        color.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
        color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
        color.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
        color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
        color.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        color.finalLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;  // ready for the blit
        VkAttachmentReference ref = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
        VkSubpassDescription sub = {};
        sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
        sub.colorAttachmentCount = 1; sub.pColorAttachments = &ref;
        VkSubpassDependency deps[2] = {};
        deps[0] = {VK_SUBPASS_EXTERNAL, 0,
                   VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                   VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT, 0};
        deps[1] = {0, VK_SUBPASS_EXTERNAL,
                   VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                   VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT, 0};
        VkRenderPassCreateInfo ci = {VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};
        ci.attachmentCount = 1; ci.pAttachments = &color;
        ci.subpassCount = 1; ci.pSubpasses = &sub;
        ci.dependencyCount = 2; ci.pDependencies = deps;
        if (vkCreateRenderPass(device_, &ci, nullptr, &renderPass_) != VK_SUCCESS) return false;

        VkFramebufferCreateInfo fb = {VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};
        fb.renderPass = renderPass_; fb.attachmentCount = 1; fb.pAttachments = &renderImage_.view;
        fb.width = width_; fb.height = height_; fb.layers = 1;
        if (vkCreateFramebuffer(device_, &fb, nullptr, &framebuffer_) != VK_SUCCESS) return false;
    }

    // ── Graphics splat pipeline (instanced quads; attr + sorted vals, vertex) ──
    dslSplat_ = makeDSL(device_, {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                                  VK_DESCRIPTOR_TYPE_STORAGE_BUFFER}, VK_SHADER_STAGE_VERTEX_BIT);
    layoutSplat_ = makePipeLayout(device_, {dslSplat_}, 2 * sizeof(uint32_t), VK_SHADER_STAGE_VERTEX_BIT);
    {
        VkShaderModule vs = makeModule(device_, splat_vert_data, sizeof(splat_vert_data));
        VkShaderModule fs = makeModule(device_, splat_frag_data, sizeof(splat_frag_data));
        VkPipelineShaderStageCreateInfo st[2] = {};
        st[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        st[0].stage = VK_SHADER_STAGE_VERTEX_BIT;   st[0].module = vs; st[0].pName = "main";
        st[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        st[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT; st[1].module = fs; st[1].pName = "main";

        VkPipelineVertexInputStateCreateInfo vi = {VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};
        VkPipelineInputAssemblyStateCreateInfo ia = {VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};
        ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP;
        VkPipelineViewportStateCreateInfo vp = {VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};
        vp.viewportCount = 1; vp.scissorCount = 1;
        VkPipelineRasterizationStateCreateInfo rs = {VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};
        rs.polygonMode = VK_POLYGON_MODE_FILL; rs.cullMode = VK_CULL_MODE_NONE;
        rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE; rs.lineWidth = 1.0f;
        VkPipelineMultisampleStateCreateInfo ms = {VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};
        ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
        VkPipelineDepthStencilStateCreateInfo dss = {VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO};
        VkPipelineColorBlendAttachmentState cba = {};
        cba.blendEnable = VK_TRUE;
        cba.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
        cba.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
        cba.colorBlendOp = VK_BLEND_OP_ADD;
        cba.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
        cba.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
        cba.alphaBlendOp = VK_BLEND_OP_ADD;
        cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                             VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
        VkPipelineColorBlendStateCreateInfo cb = {VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};
        cb.attachmentCount = 1; cb.pAttachments = &cba;
        VkDynamicState dyn[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
        VkPipelineDynamicStateCreateInfo dynci = {VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};
        dynci.dynamicStateCount = 2; dynci.pDynamicStates = dyn;
        VkGraphicsPipelineCreateInfo gci = {VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};
        gci.stageCount = 2; gci.pStages = st;
        gci.pVertexInputState = &vi; gci.pInputAssemblyState = &ia;
        gci.pViewportState = &vp; gci.pRasterizationState = &rs;
        gci.pMultisampleState = &ms; gci.pDepthStencilState = &dss;
        gci.pColorBlendState = &cb; gci.pDynamicState = &dynci;
        gci.layout = layoutSplat_; gci.renderPass = renderPass_; gci.subpass = 0;
        VkResult pr = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &gci, nullptr, &pipeSplat_);
        vkDestroyShaderModule(device_, vs, nullptr);
        vkDestroyShaderModule(device_, fs, nullptr);
        if (pr != VK_SUCCESS) return false;
    }

    // ── Descriptor sets ──
    dsCov3d_ = allocDS(device_, descriptorPool_, dslCov3d_);
    writeDS(device_, dsCov3d_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, vertexBuffer_.buffer, vertexBuffer_.size);
    writeDS(device_, dsCov3d_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, cov3dBuffer_.buffer, cov3dBuffer_.size);

    dsPreprocessSet0_ = allocDS(device_, descriptorPool_, dslPreprocessSet0_);
    writeDS(device_, dsPreprocessSet0_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, vertexBuffer_.buffer, vertexBuffer_.size);
    writeDS(device_, dsPreprocessSet0_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, cov3dBuffer_.buffer, cov3dBuffer_.size);
    // One descriptor set per ring slot, each binding its own uniform (binding 0);
    // attrBuffer_ (binding 1) is shared. renderEye binds dsPreprocessSet1_[slot].
    for (uint32_t s = 0; s < kFrameRing; s++) {
        dsPreprocessSet1_[s] = allocDS(device_, descriptorPool_, dslPreprocessSet1_);
        writeDS(device_, dsPreprocessSet1_[s], 0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
                uniformBuffer_[s].buffer, uniformBuffer_[s].size);
        writeDS(device_, dsPreprocessSet1_[s], 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                attrBuffer_.buffer, attrBuffer_.size);
    }

    dsKeys_ = allocDS(device_, descriptorPool_, dslKeys_);
    writeDS(device_, dsKeys_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, attrBuffer_.buffer, attrBuffer_.size);
    writeDS(device_, dsKeys_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysEvenBuffer_.buffer, keysEvenBuffer_.size);
    writeDS(device_, dsKeys_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, valsEvenBuffer_.buffer, valsEvenBuffer_.size);

    dsHistEven_ = allocDS(device_, descriptorPool_, dslHist_);
    writeDS(device_, dsHistEven_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysEvenBuffer_.buffer, keysEvenBuffer_.size);
    writeDS(device_, dsHistEven_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, histBuffer_.buffer, histBuffer_.size);
    dsHistOdd_ = allocDS(device_, descriptorPool_, dslHist_);
    writeDS(device_, dsHistOdd_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysOddBuffer_.buffer, keysOddBuffer_.size);
    writeDS(device_, dsHistOdd_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, histBuffer_.buffer, histBuffer_.size);

    dsSortEvenToOdd_ = allocDS(device_, descriptorPool_, dslSort_);
    writeDS(device_, dsSortEvenToOdd_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysEvenBuffer_.buffer, keysEvenBuffer_.size);
    writeDS(device_, dsSortEvenToOdd_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysOddBuffer_.buffer, keysOddBuffer_.size);
    writeDS(device_, dsSortEvenToOdd_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, valsEvenBuffer_.buffer, valsEvenBuffer_.size);
    writeDS(device_, dsSortEvenToOdd_, 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, valsOddBuffer_.buffer, valsOddBuffer_.size);
    writeDS(device_, dsSortEvenToOdd_, 4, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, histBuffer_.buffer, histBuffer_.size);
    dsSortOddToEven_ = allocDS(device_, descriptorPool_, dslSort_);
    writeDS(device_, dsSortOddToEven_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysOddBuffer_.buffer, keysOddBuffer_.size);
    writeDS(device_, dsSortOddToEven_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, keysEvenBuffer_.buffer, keysEvenBuffer_.size);
    writeDS(device_, dsSortOddToEven_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, valsOddBuffer_.buffer, valsOddBuffer_.size);
    writeDS(device_, dsSortOddToEven_, 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, valsEvenBuffer_.buffer, valsEvenBuffer_.size);
    writeDS(device_, dsSortOddToEven_, 4, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, histBuffer_.buffer, histBuffer_.size);

    dsSplat_ = allocDS(device_, descriptorPool_, dslSplat_);
    writeDS(device_, dsSplat_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, attrBuffer_.buffer, attrBuffer_.size);
    writeDS(device_, dsSplat_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, valsEvenBuffer_.buffer, valsEvenBuffer_.size);

    return true;
}

// ═══════════════════════════ dispatchCov3d (once) ═══════════════════════════

void GsAdrenoRenderer::dispatchCov3d() {
    VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    ai.commandPool = cmdPool_; ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; ai.commandBufferCount = 1;
    VkCommandBuffer cmd; vkAllocateCommandBuffers(device_, &ai, &cmd);
    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeCov3d_);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layoutCov3d_, 0, 1, &dsCov3d_, 0, nullptr);
    float scale_factor = 1.0f;
    vkCmdPushConstants(cmd, layoutCov3d_, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(float), &scale_factor);
    vkCmdDispatch(cmd, (numGaussians_ + 255) / 256, 1, 1);
    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1; si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
}

// ═══════════════════════════ updateUniforms ═════════════════════════════════

void GsAdrenoRenderer::updateUniforms(uint32_t slot, const float viewMatrix[16], const float projMatrix[16],
                                      uint32_t vpWidth, uint32_t vpHeight,
                                      float clipNear, float clipFar, float clipFadeFrac) {
    GsUniformBuffer ub;
    // Camera position from the view matrix: cam = -R^T·t (column-major).
    float tx = viewMatrix[12], ty = viewMatrix[13], tz = viewMatrix[14];
    ub.camera_position[0] = -(viewMatrix[0]*tx + viewMatrix[1]*ty + viewMatrix[2]*tz);
    ub.camera_position[1] = -(viewMatrix[4]*tx + viewMatrix[5]*ty + viewMatrix[6]*tz);
    ub.camera_position[2] = -(viewMatrix[8]*tx + viewMatrix[9]*ty + viewMatrix[10]*tz);
    ub.camera_position[3] = 1.0f;
    // proj_mat = projMatrix · viewMatrix (column-major multiply).
    for (int col = 0; col < 4; col++)
        for (int row = 0; row < 4; row++) {
            float s = 0.0f;
            for (int k = 0; k < 4; k++) s += projMatrix[k*4+row] * viewMatrix[col*4+k];
            ub.proj_mat[col*4+row] = s;
        }
    // view_mat: negate Z row (OpenXR -Z forward → shader +Z forward).
    memcpy(ub.view_mat, viewMatrix, 16 * sizeof(float));
    ub.view_mat[2] = -ub.view_mat[2]; ub.view_mat[6] = -ub.view_mat[6];
    ub.view_mat[10] = -ub.view_mat[10]; ub.view_mat[14] = -ub.view_mat[14];
    ub.width = vpWidth; ub.height = vpHeight;
    float p00 = projMatrix[0], p11 = projMatrix[5];
    ub.tan_fovx = (std::abs(p00) > 1e-6f) ? (1.0f / std::abs(p00)) : 1.0f;
    ub.tan_fovy = (std::abs(p11) > 1e-6f) ? (1.0f / std::abs(p11)) : 1.0f;
    ub.clip_far = clipFar; ub.clip_fade_frac = clipFadeFrac; ub.clip_near = clipNear;
    void* m = nullptr;
    vkMapMemory(device_, uniformBuffer_[slot].memory, 0, sizeof(GsUniformBuffer), 0, &m);
    memcpy(m, &ub, sizeof(GsUniformBuffer));
    vkUnmapMemory(device_, uniformBuffer_[slot].memory);
}

// ═══════════════════════════════ renderEye ══════════════════════════════════

void GsAdrenoRenderer::renderEye(VkImage swapchainImage, VkFormat /*swapchainFormat*/,
                                 uint32_t /*imageWidth*/, uint32_t /*imageHeight*/,
                                 uint32_t viewportX, uint32_t viewportY,
                                 uint32_t viewportWidth, uint32_t viewportHeight,
                                 const float viewMatrix[16], const float projMatrix[16],
                                 bool /*transparentBg*/, float clipNearViewSpace,
                                 float clipFarViewSpace, float clipFadeFrac) {
    if (!sceneLoaded_) return;
    const uint32_t N = numGaussians_;

    // Scaled internal render dims.
    uint32_t rw = (uint32_t)std::lround(viewportWidth * renderScale_);
    uint32_t rh = (uint32_t)std::lround(viewportHeight * renderScale_);
    if (rw < 1) rw = 1; if (rh < 1) rh = 1;
    if (rw > width_) rw = width_; if (rh > height_) rh = height_;

    // updateUniforms is deferred to AFTER this eye's ring-slot fence wait below —
    // writing the shared-host-visible UBO here (before the wait) let the next eye
    // clobber an in-flight eye's matrices → left-eye judder (#44 review).

    // Per-eye depth-quant range: project the cached scene bbox corners to view
    // depth, pad 2%, clamp to the cull window (matches the desktop derivation).
    float depthQMin = 0.2f, depthQMax = 100.2f;
    if (sceneBBoxValid_) {
        float mn = FLT_MAX, mx = -FLT_MAX;
        for (int ci = 0; ci < 8; ci++) {
            float cx = (ci & 1) ? sceneBBoxMax_[0] : sceneBBoxMin_[0];
            float cy = (ci & 2) ? sceneBBoxMax_[1] : sceneBBoxMin_[1];
            float cz = (ci & 4) ? sceneBBoxMax_[2] : sceneBBoxMin_[2];
            float d = -(viewMatrix[2]*cx + viewMatrix[6]*cy + viewMatrix[10]*cz + viewMatrix[14]);
            mn = std::min(mn, d); mx = std::max(mx, d);
        }
        float pad = 0.02f * (mx - mn); mn -= pad; mx += pad;
        if (clipNearViewSpace > 0.0f) mn = std::max(mn, clipNearViewSpace);
        if (clipFarViewSpace > 0.0f) mx = std::min(mx, clipFarViewSpace);
        mn = std::max(mn, 0.2f);
        if (mx > mn + 1e-6f) { depthQMin = mn; depthQMax = mx; }
    }

    // Pipelining ring: wait only on THIS slot's fence (its prior submit was
    // kFrameRing eyes ago — already finished in steady state). No global
    // vkQueueWaitIdle, so the app's GPU work overlaps the runtime/DP weave and
    // the next eye/frame instead of CPU-blocking on every eye.
    const uint32_t slot = (uint32_t)(frameCounter_ % kFrameRing);
    vkWaitForFences(device_, 1, &ringFence_[slot], VK_TRUE, UINT64_MAX);

    const bool tsOn = (timestampPeriod_ > 0.0f && tsPool_[slot] != VK_NULL_HANDLE);
    VkQueryPool tsq = tsOn ? tsPool_[slot] : VK_NULL_HANDLE;

    // This slot's fence is now signaled → its PREVIOUS timestamps are ready.
    if (tsOn && frameCounter_ >= kFrameRing && (frameCounter_ % 120) == 0) {
        uint64_t ts[kNumTimestamps] = {};
        if (vkGetQueryPoolResults(device_, tsq, 0, kNumTimestamps, sizeof(ts), ts,
                sizeof(uint64_t), VK_QUERY_RESULT_64_BIT) == VK_SUCCESS) {
            const uint64_t mask = (tsValidBits_ >= 64) ? ~0ULL : ((1ULL << tsValidBits_) - 1ULL);
            auto ms = [&](uint32_t a, uint32_t b) -> double {
                return (double)((ts[b] & mask) - (ts[a] & mask)) * (double)timestampPeriod_ / 1.0e6; };
            GS_LOGI("GS_TS[adreno] N=%u render=%ux%u(scale=%.2f keep=%.2f) | preproc=%.2f keygen=%.2f "
                    "radix=%.2f draw=%.2f blit=%.2f | TOTAL=%.2f ms",
                    N, rw, rh, renderScale_, keepFrac_, ms(0,1), ms(1,2), ms(2,3), ms(3,4), ms(4,5), ms(0,5));
        }
    }

    vkResetFences(device_, 1, &ringFence_[slot]);

    // Now that THIS slot's prior submit has retired, write its own per-slot UBO —
    // no other in-flight eye reads uniformBuffer_[slot], so no race (#44 review fix).
    updateUniforms(slot, viewMatrix, projMatrix, rw, rh, clipNearViewSpace, clipFarViewSpace, clipFadeFrac);

    VkCommandBuffer cmd = ringCmd_[slot];
    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);  // implicit reset (pool: RESET_COMMAND_BUFFER_BIT)

    if (tsOn) {
        vkCmdResetQueryPool(cmd, tsq, 0, kNumTimestamps);
        vkCmdWriteTimestamp(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, tsq, 0);
    }

    VkMemoryBarrier mb = {VK_STRUCTURE_TYPE_MEMORY_BARRIER};
    auto computeBarrier = [&]() {
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);
    };

    // ── 1. preprocess: project + conic + SH + depth → attr[] ──
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipePreprocess_);
    VkDescriptorSet pp[] = {dsPreprocessSet0_, dsPreprocessSet1_[slot]};
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layoutPreprocess_, 0, 2, pp, 0, nullptr);
    vkCmdDispatch(cmd, (N + 255) / 256, 1, 1);
    computeBarrier();
    if (tsOn) vkCmdWriteTimestamp(cmd, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, tsq, 1);

    // ── 2. keygen: far-first depth key + index payload ──
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeKeys_);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layoutKeys_, 0, 1, &dsKeys_, 0, nullptr);
    struct { uint32_t count; float depthMin; float invRange; }
        kpc = {N, depthQMin, 65535.0f / (depthQMax - depthQMin)};
    vkCmdPushConstants(cmd, layoutKeys_, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(kpc), &kpc);
    vkCmdDispatch(cmd, (N + 255) / 256, 1, 1);
    computeBarrier();
    if (tsOn) vkCmdWriteTimestamp(cmd, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, tsq, 2);

    // ── 3. radix sort N keys. The depth key (splat_keys.comp: 65535-depth16)
    //    is only 16-bit, so just 2 of the 4 8-bit passes carry information —
    //    bits 16-31 are always zero for valid keys. Sorting 2 passes instead of
    //    4 halves the radix cost (the dominant stage) with NO ordering change;
    //    culled keys (0xFFFFFFFF) still land last by their low-16 (0xFFFF) and
    //    draw as degenerate quads anyway. 2 passes → result back in EVEN. ──
    constexpr uint32_t kRadixPasses = 2;  // 16-bit depth key
    struct RadixPC { uint32_t num_elements, shift, num_workgroups, num_blocks_per_workgroup; };
    for (uint32_t pass = 0; pass < kRadixPasses; pass++) {
        bool even = (pass % 2 == 0);
        RadixPC pc = {N, pass * 8, numSortWorkgroups_, numRadixBlocksPerWG_};
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeHist_);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layoutHist_, 0, 1,
            even ? &dsHistEven_ : &dsHistOdd_, 0, nullptr);
        vkCmdPushConstants(cmd, layoutHist_, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);
        vkCmdDispatch(cmd, numSortWorkgroups_, 1, 1);
        computeBarrier();
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeSort_);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layoutSort_, 0, 1,
            even ? &dsSortEvenToOdd_ : &dsSortOddToEven_, 0, nullptr);
        vkCmdPushConstants(cmd, layoutSort_, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);
        vkCmdDispatch(cmd, numSortWorkgroups_, 1, 1);
        computeBarrier();
    }
    if (tsOn) vkCmdWriteTimestamp(cmd, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, tsq, 3);

    // Make attr[] + sorted payloads visible to the vertex shader.
    mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_VERTEX_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

    // ── 4. instanced alpha-blended quad draw into renderImage_ (scaled region) ──
    VkClearValue clear = {}; clear.color = {{0.0f, 0.0f, 0.0f, 0.0f}};
    VkRenderPassBeginInfo rp = {VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};
    rp.renderPass = renderPass_; rp.framebuffer = framebuffer_;
    rp.renderArea = {{0, 0}, {rw, rh}};
    rp.clearValueCount = 1; rp.pClearValues = &clear;
    vkCmdBeginRenderPass(cmd, &rp, VK_SUBPASS_CONTENTS_INLINE);
    VkViewport vpt = {0.0f, 0.0f, (float)rw, (float)rh, 0.0f, 1.0f};
    VkRect2D sc = {{0, 0}, {rw, rh}};
    vkCmdSetViewport(cmd, 0, 1, &vpt);
    vkCmdSetScissor(cmd, 0, 1, &sc);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeSplat_);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, layoutSplat_, 0, 1, &dsSplat_, 0, nullptr);
    uint32_t splatPC[2] = {rw, rh};
    vkCmdPushConstants(cmd, layoutSplat_, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(splatPC), splatPC);
    vkCmdDraw(cmd, 4, N, 0, 0);
    vkCmdEndRenderPass(cmd);  // renderImage_ now in TRANSFER_SRC_OPTIMAL
    if (tsOn) vkCmdWriteTimestamp(cmd, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, tsq, 4);

    // ── 5. blit (linear upscale) the scaled region to the swapchain viewport ──
    VkImageMemoryBarrier sb = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
    sb.srcAccessMask = 0; sb.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    sb.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    sb.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    sb.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; sb.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    sb.image = swapchainImage;
    sb.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
        0, 0, nullptr, 0, nullptr, 1, &sb);

    VkImageBlit blit = {};
    blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    blit.srcOffsets[0] = {0, 0, 0};
    blit.srcOffsets[1] = {(int32_t)rw, (int32_t)rh, 1};
    blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    blit.dstOffsets[0] = {(int32_t)viewportX, (int32_t)viewportY, 0};
    blit.dstOffsets[1] = {(int32_t)(viewportX + viewportWidth), (int32_t)(viewportY + viewportHeight), 1};
    VkFilter filter = (rw == viewportWidth && rh == viewportHeight) ? VK_FILTER_NEAREST : VK_FILTER_LINEAR;
    vkCmdBlitImage(cmd, renderImage_.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        swapchainImage, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, filter);

    sb.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    sb.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    sb.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    sb.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
        VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, 0, 0, nullptr, 0, nullptr, 1, &sb);
    if (tsOn) vkCmdWriteTimestamp(cmd, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, tsq, 5);

    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1; si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, ringFence_[slot]);  // fence (not waitIdle) → pipelined
    frameCounter_++;
}

// ═══════════════════════════ getRobustSceneBounds ═══════════════════════════

bool GsAdrenoRenderer::getRobustSceneBounds(float loPct, float hiPct,
                                            float outCenter[3], float outExtent[3]) const {
    if (numGaussians_ == 0) return false;
    if (loPct < 0.0f) loPct = 0.0f;
    if (hiPct > 1.0f) hiPct = 1.0f;
    if (hiPct <= loPct) { hiPct = loPct + 1e-3f; if (hiPct > 1.0f) hiPct = 1.0f; }
    const size_t n = numGaussians_;
    const float* src[3] = {posX_.data(), posY_.data(), posZ_.data()};
    std::vector<float> coord(n);
    for (int a = 0; a < 3; a++) {
        std::copy(src[a], src[a] + n, coord.begin());
        size_t lo = (size_t)(loPct * (float)(n - 1));
        size_t hi = (size_t)(hiPct * (float)(n - 1));
        if (hi <= lo) hi = lo + 1;
        if (hi >= n) hi = n - 1;
        std::nth_element(coord.begin(), coord.begin() + lo, coord.end());
        float lov = coord[lo];
        std::nth_element(coord.begin() + lo + 1, coord.begin() + hi, coord.end());
        float hiv = coord[hi];
        outCenter[a] = 0.5f * (lov + hiv);
        outExtent[a] = hiv - lov;
    }
    return true;
}

bool GsAdrenoRenderer::pickGaussian(const float rayOrigin[3], const float rayDir[3],
                                    float hitPos[3], float maxDistance) const {
    if (numGaussians_ == 0) return false;

    // Scene-relative hit radius: a tap "hits" if the ray passes within ~12% of the
    // scene's largest extent of a gaussian center — forgiving on a touchscreen
    // without latching onto far-off floaters.
    float c[3], e[3];
    float maxPerp = 0.2f;
    if (getRobustSceneBounds(0.02f, 0.98f, c, e)) {
        float m = e[0] > e[1] ? e[0] : e[1];
        m = m > e[2] ? m : e[2];
        if (m > 1e-4f) maxPerp = 0.12f * m;
    }
    const float maxPerp2 = maxPerp * maxPerp;

    // Front-most gaussian center the ray passes within maxPerp of.
    float bestT = 1e30f;
    int bestIdx = -1;
    for (uint32_t i = 0; i < numGaussians_; i++) {
        const float dx = posX_[i] - rayOrigin[0];
        const float dy = posY_[i] - rayOrigin[1];
        const float dz = posZ_[i] - rayOrigin[2];
        const float t = dx * rayDir[0] + dy * rayDir[1] + dz * rayDir[2];
        if (t < 0.05f || t > maxDistance) continue; // behind the eye / too far
        const float px = dx - t * rayDir[0];
        const float py = dy - t * rayDir[1];
        const float pz = dz - t * rayDir[2];
        const float perp2 = px * px + py * py + pz * pz;
        if (perp2 > maxPerp2) continue;
        if (t < bestT) { bestT = t; bestIdx = (int)i; }
    }
    if (bestIdx < 0) return false;
    hitPos[0] = posX_[bestIdx];
    hitPos[1] = posY_[bestIdx];
    hitPos[2] = posZ_[bestIdx];
    return true;
}

// ═══════════════════════════════ cleanup ════════════════════════════════════

void GsAdrenoRenderer::cleanupScene() {
    if (device_ == VK_NULL_HANDLE) return;
    vkQueueWaitIdle(queue_);
    auto dp = [&](VkPipeline& p){ if (p) { vkDestroyPipeline(device_, p, nullptr); p = VK_NULL_HANDLE; } };
    auto dl = [&](VkPipelineLayout& l){ if (l) { vkDestroyPipelineLayout(device_, l, nullptr); l = VK_NULL_HANDLE; } };
    auto ds = [&](VkDescriptorSetLayout& l){ if (l) { vkDestroyDescriptorSetLayout(device_, l, nullptr); l = VK_NULL_HANDLE; } };

    dp(pipeCov3d_); dp(pipePreprocess_); dp(pipeKeys_); dp(pipeHist_); dp(pipeSort_); dp(pipeSplat_);
    if (framebuffer_) { vkDestroyFramebuffer(device_, framebuffer_, nullptr); framebuffer_ = VK_NULL_HANDLE; }
    if (renderPass_) { vkDestroyRenderPass(device_, renderPass_, nullptr); renderPass_ = VK_NULL_HANDLE; }
    dl(layoutCov3d_); dl(layoutPreprocess_); dl(layoutKeys_); dl(layoutHist_); dl(layoutSort_); dl(layoutSplat_);
    ds(dslCov3d_); ds(dslPreprocessSet0_); ds(dslPreprocessSet1_); ds(dslKeys_); ds(dslHist_); ds(dslSort_); ds(dslSplat_);
    if (descriptorPool_) { vkDestroyDescriptorPool(device_, descriptorPool_, nullptr); descriptorPool_ = VK_NULL_HANDLE; }
    dsCov3d_ = dsPreprocessSet0_ = dsKeys_ = VK_NULL_HANDLE;
    for (uint32_t s = 0; s < kFrameRing; s++) dsPreprocessSet1_[s] = VK_NULL_HANDLE;
    dsHistEven_ = dsHistOdd_ = dsSortEvenToOdd_ = dsSortOddToEven_ = dsSplat_ = VK_NULL_HANDLE;

    gsDestroyImage(device_, renderImage_);
    gsDestroyBuffer(device_, vertexBuffer_); gsDestroyBuffer(device_, cov3dBuffer_);
    for (uint32_t s = 0; s < kFrameRing; s++) gsDestroyBuffer(device_, uniformBuffer_[s]);
    gsDestroyBuffer(device_, attrBuffer_);
    gsDestroyBuffer(device_, keysEvenBuffer_); gsDestroyBuffer(device_, keysOddBuffer_);
    gsDestroyBuffer(device_, valsEvenBuffer_); gsDestroyBuffer(device_, valsOddBuffer_);
    gsDestroyBuffer(device_, histBuffer_);

    posX_.clear(); posY_.clear(); posZ_.clear();
    sceneBBoxValid_ = false;
    numGaussians_ = 0;
    sceneLoaded_ = false;
    loadedScenePath_.clear();
}

void GsAdrenoRenderer::cleanup() {
    if (device_ == VK_NULL_HANDLE) return;
    cleanupScene();
    if (queue_) vkQueueWaitIdle(queue_);  // ring submits may be in flight
    for (uint32_t i = 0; i < kFrameRing; i++) {
        if (tsPool_[i]) { vkDestroyQueryPool(device_, tsPool_[i], nullptr); tsPool_[i] = VK_NULL_HANDLE; }
        if (ringFence_[i]) { vkDestroyFence(device_, ringFence_[i], nullptr); ringFence_[i] = VK_NULL_HANDLE; }
    }
    ringReady_ = false;
    if (cmdPool_) { vkDestroyCommandPool(device_, cmdPool_, nullptr); cmdPool_ = VK_NULL_HANDLE; }
    initialized_ = false;
}

GsAdrenoRenderer::~GsAdrenoRenderer() { cleanup(); }
